### ISSUE TITLE
No good ratio in 4/3 mode 

### ISSUE THREAD

**Issue by bilippe** [MiSTer-devel/SNES_MiSTer#124]
Hello, could you redefine the ratio for 4/3 display (HDMI Mode). In fact, the ratio in 4/3 mode displays a ratio of 1.28 instead of 1.33 (4/3). For example, NeoGeo Core has a good display in proportions and Genesis too. (original mode and 304px for NG / 320*224 aspect : "Corrected ")
Nes, Snes, Sega Master System and Pc Engine display in 4/3 mode has this issue too....
Thanks in advance for a real 4/3 ratio like 20years ago!

**Comment by Kitrinx** [comment]
SNES and NES real consoles both output a 280 x 240 resolution, with 256 drawn pixels and the rest being solid colored padding in the case of the NES, or masked black space in the case of SNES. A CRT television would then scale this 280 x 240 image into a 4:3 area. Because MiSTer only deals with the drawn areas, which are either 256x224 for SNES and cropped NES, or 256x240 for full height NES, therefor the aspect ratio must be adjusted to 64:49 or 128:105 respectively, which it is. 

It's been confirmed to be accurate by comparing it to CRT output, and discussed ad nausium. If you try 240p test suite's linearity tests you can see for yourself.
