### ISSUE TITLE
Secret of Evermore bug on broken dialog

### ISSUE THREAD

**Issue by theypsilon** [MiSTer-devel/SNES_MiSTer#313]
![imagen](https://user-images.githubusercontent.com/852246/150196225-fb6ccaff-4ff4-4a79-806e-224d2e70deb3.png)

Savegame close to that place attached. Just go to fight Tiny and you'll see it.

[SOE.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/7899903/SOE.zip)

It's a bug on real hardware, so accurate emulators should show this.

Closing issue. This was just to document this finding.

**Comment by bootsector** [comment]
Thanks for documenting this! 

Taking advantage of this issue tracking, this is the bug that will prevent you to complete the game forever and that I was able to find out and trigger. 

I think this happens when you get the Gauge twice (known bug that makes second gauge work as Diamond Eyes), then the Wheel then finally the Diamond Eyes by defeating Tiny. 

Just open third save and check the bag of charms that there are the Gauge, Wheel and Diamond Eyes. After leaving the Inn, go far east and get the flying machine and go see Tinker. Talk to him twice then check the bag of charms. You got only a Gauge and no Wheel nor Diamond Eyes. 

Since there's no way to get another Wheel in Bugmuck, you are unable to finish the game forever!

[Secret of Evermore (USA).sav.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/7914429/Secret.of.Evermore.USA.sav.zip)

**Comment by Max833** [comment]
Thank you!
