### ISSUE TITLE
No game runs?

### ISSUE THREAD

**Issue by jeffbdavenport** [MiSTer-devel/SNES_MiSTer#355]
Is it just me? I can't get any SNES game to run on any of the releases. Best I can get is some of them will get to the intro of the game and as soon as you click play it freezes. 

Yes I have the 32MB SDRAM. All NES and Genesis games run just fine.

I got Quartus Prime all setup and running to try a troubleshoot, but I have no idea where to even begin to start looking.

**Comment by birdybro** [comment]
Can you provide a picture of your SDRAM as installed?

Can you load games in the NES core?

**Comment by jeffbdavenport** [comment]
![image](https://user-images.githubusercontent.com/17709993/217594201-12ebdd17-2afb-4ef1-8985-12c816592861.jpeg)

Yes I can load the NES core as well as any games and they all run flawlessly

**Comment by birdybro** [comment]
That SDRAM v3.1 is 5.5 years old. It's a collector's item! :)

My first inclination is to suggest that you upgrade to a modern SDRAM module since it's possible that this model isn't wired up identically and the SNES core might be taking advantage of a line that isn't present.

Something I noticed is that multiple pins do not have the proper amount of solder so you may have signal integrity issues or even a full disconnection if it gets even slightly budged.

![image](https://user-images.githubusercontent.com/16388068/217764413-2066604c-a9fa-412d-b7c7-3a817922d8ff.png)

**Comment by jeffbdavenport** [comment]
Interesting, I thank you for your insight, I was suspicious that it was the Ram but was confused that memory tests ran just fine and other cores worked fine as well, I will try to get the latest SDRAM version
