### ISSUE TITLE
Mecarobot Golf - [HDMA related] Flickering during gameplay

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/SNES_MiSTer#97]
Here's a clip of it running on the MiSTer, this is the USA ROM. 

https://gfycat.com/alertidlehadrosaurus

According to the following article, flickering in this game is often caused by the HDMA timings being off

http://helmet.kafuka.org/accuracy/

Thanks! Really love this core in general, it is very high quality and accurate. I am extremely impressed :)

EDIT: I tested this as of 8b5f60484dac5675db4ecdb4cb485f8c5b0d7f20

**Comment by James-F2** [comment]
This is one of the very few games that uses 239p mode, so HDMA might be affect by the non typical resolution.

**Comment by James-F2** [comment]
@srg320 
At this stage Mesen-S is more accurate than bsnes and has better debugger than bsnes-plus.
I thought this might give the core the last push with a great reference.
https://github.com/SourMesen/Mesen-S

**Comment by srg320** [comment]
Has better debugger  - it's true, but more accurate than bsnes - I'm not sure.

**Comment by MP2E** [comment]
I noticed there were some mode 7 changes so I just wanted to report that the game still has the same visual bug as of latest commit

**Comment by MP2E** [comment]
This seems to flicker less as of #148 ! However unfortunately, the issue is still present

**Comment by James-F2** [comment]
Are we sure it's HDMA related?
Seems to be Mode7 not calculated fast enough since I see a flicker of the entire map from above for a frame... or so it appears to me.

**Comment by MP2E** [comment]
I'm not sure if it's hdma related at this point. It's hard to say

**Comment by James-F2** [comment]
If a background layer (Mode 7) is inserted from the middle of the screen, it is some kind of DMA/HDMA related trick.

**Comment by srg320** [comment]
@James-F2
This is it..

**Comment by paulb-nl** [comment]
It seems the flicker is caused by an IRQ/DRAM refresh issue. There is an IRQ in the mode 7 layer that is close to the refresh and sometimes this IRQ is delayed until after the refresh or the IRQ is not triggered at all. That does not happen in Mesen-S.

The flicker does not happen on a build with DRAM refresh disabled.

Here are videos which show yellow lines where 'IsIRQInterrupt' is high.
Refresh enabled: [https://youtu.be/faGqxFDCIlw](https://youtu.be/faGqxFDCIlw)

Refresh disabled: [https://youtu.be/mYBNUaqAJeU](https://youtu.be/mYBNUaqAJeU)

You can pause the video and press , and . to advance frames.

**Comment by James-F2** [comment]
https://github.com/MiSTer-devel/SNES_MiSTer/pull/177
This seems to fix that. :)

**Comment by srg320** [comment]
Oh, unexpectedly.

**Comment by James-F2** [comment]
Could be just my build.
Needs confirmation by another person.

**Comment by MP2E** [comment]
I'm amazed! It does seem to be fixed by that commit. Completely eliminated all flickering. Thanks again!
